server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/schoolms
    username: postgres
    password: Crt@Ailsa

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  jwt:
    secret: U2Nob29sTVNhdXBlclNlY3JldEtleUZvckpXVE1VU1RCZUxvbmdFbm91Z2g=
    expiration-ms: 86400000
  seed-demo-data: false
