package com.schoolms.student;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDate;

public record StudentCreateRequest(
        @NotBlank(message = "First name is required") String firstName,
        String middleName,
        @NotBlank(message = "Last name is required") String lastName,
        String preferredName,
        @NotBlank(message = "Admission number is required") String admissionNumber,
        @NotBlank(message = "Gender is required") String gender,
        LocalDate dateOfBirth,
        @NotBlank(message = "Grade is required") String grade,
        @NotNull(message = "Enrollment date is required") LocalDate enrollmentDate,
        String guardianName,
        String guardianRelationship,
        String guardianPhone,
        String address,
        @NotNull(message = "Status is required") StudentStatus status,
        String nationality,
        String nationalId,
        String passportNumber,
        String previousSchool,
        String phoneNumber,
        String alternativePhoneNumber,
        String email,
        String addressLine1,
        String addressLine2,
        String city,
        String district,
        String postalCode,
        String country,
        String guardianAltPhone,
        String guardianEmail,
        String guardianOccupation,
        String guardianAddress,
        String emergencyContactName,
        String emergencyContactPhone,
        String emergencyContactRelationship,
        String bloodGroup,
        String allergies,
        String medicalConditions,
        String disabilities,
        String medication,
        String hospitalName,
        String doctorName,
        String doctorPhone,
        Boolean usesTransport,
        String pickupPoint,
        String routeName,
        String driverAssignment,
        String religion,
        String homeLanguage,
        String residencyType,
        String sponsorshipStatus,
        String feeCategory,
        String notes,
        Long schoolClassId
) {
}
