package com.schoolms.student;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Past;
import jakarta.validation.constraints.Pattern;
import java.time.LocalDate;

public class StudentDtos {
    public record StudentRequest(
            @NotBlank(message = "Admission number is required") String admissionNumber,
            @NotBlank(message = "First name is required") String firstName,
            String middleName,
            @NotBlank(message = "Last name is required") String lastName,
            String preferredName,
            @NotBlank(message = "Gender is required")
            @Pattern(regexp = "MALE|FEMALE|OTHER", message = "Gender must be one of: MALE, FEMALE, OTHER") String gender,
            @Past(message = "Date of birth must be in the past") LocalDate dateOfBirth,
            String grade,
            @NotNull(message = "Class is required") Long classId,
            @NotNull(message = "Enrollment date is required") LocalDate enrollmentDate,
            String guardianName,
            String guardianRelationship,
            String guardianPhone,
            String address,
            StudentStatus status,
            String nationality,
            String nationalId,
            String passportNumber,
            String previousSchool,
            String phoneNumber,
            String alternativePhoneNumber,
            String email,
            String addressLine1,
            String addressLine2,
            String city,
            String district,
            String postalCode,
            String country,
            String guardianAltPhone,
            String guardianEmail,
            String guardianOccupation,
            String guardianAddress,
            String emergencyContactName,
            String emergencyContactPhone,
            String emergencyContactRelationship,
            String bloodGroup,
            String allergies,
            String medicalConditions,
            String disabilities,
            String medication,
            String hospitalName,
            String doctorName,
            String doctorPhone,
            Boolean usesTransport,
            String pickupPoint,
            String routeName,
            String driverAssignment,
            String religion,
            String homeLanguage,
            String residencyType,
            String sponsorshipStatus,
            String feeCategory,
            String notes
    ) {
    }

    public record StudentResponse(
            Long id,
            String admissionNumber,
            String firstName,
            String middleName,
            String lastName,
            String fullName,
            String preferredName,
            String gender,
            LocalDate dateOfBirth,
            String grade,
            Long classId,
            String className,
            String classStream,
            LocalDate enrollmentDate,
            String guardianName,
            String guardianRelationship,
            String guardianPhone,
            String address,
            StudentStatus status,
            String nationality,
            String nationalId,
            String passportNumber,
            String previousSchool,
            String phoneNumber,
            String alternativePhoneNumber,
            String email,
            String addressLine1,
            String addressLine2,
            String city,
            String district,
            String postalCode,
            String country,
            String guardianAltPhone,
            String guardianEmail,
            String guardianOccupation,
            String guardianAddress,
            String emergencyContactName,
            String emergencyContactPhone,
            String emergencyContactRelationship,
            String bloodGroup,
            String allergies,
            String medicalConditions,
            String disabilities,
            String medication,
            String hospitalName,
            String doctorName,
            String doctorPhone,
            Boolean usesTransport,
            String pickupPoint,
            String routeName,
            String driverAssignment,
            String religion,
            String homeLanguage,
            String residencyType,
            String sponsorshipStatus,
            String feeCategory,
            String notes
    ) {
    }
}
