package com.schoolms.student;

import com.fasterxml.jackson.annotation.JsonAlias;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDate;

public record StudentCreateRequest(
        @NotBlank(message = "Required field missing: firstName") String firstName,
        String middleName,
        @NotBlank(message = "Required field missing: lastName") String lastName,
        String preferredName,
        @NotBlank(message = "Required field missing: admissionNumber") String admissionNumber,
        @NotBlank(message = "Required field missing: gender") String gender,
        @NotNull(message = "Required field missing: dateOfBirth") LocalDate dateOfBirth,
        @NotBlank(message = "Required field missing: grade") String grade,
        @NotNull(message = "Required field missing: enrollmentDate") LocalDate enrollmentDate,
        @NotBlank(message = "Required field missing: guardianName") String guardianName,
        @NotBlank(message = "Required field missing: guardianRelationship") String guardianRelationship,
        @NotBlank(message = "Required field missing: guardianPhone") String guardianPhone,
        @NotBlank(message = "Required field missing: address") String address,
        @NotNull(message = "Required field missing: status") StudentStatus status,
        String nationality,
        String nationalId,
        String passportNumber,
        String previousSchool,
        String phoneNumber,
        String alternativePhoneNumber,
        String email,
        String addressLine1,
        String addressLine2,
        String city,
        String district,
        String postalCode,
        String country,
        String guardianAltPhone,
        String guardianEmail,
        String guardianOccupation,
        String guardianAddress,
        String emergencyContactName,
        String emergencyContactPhone,
        String emergencyContactRelationship,
        String bloodGroup,
        String allergies,
        String medicalConditions,
        String disabilities,
        String medication,
        String hospitalName,
        String doctorName,
        String doctorPhone,
        Boolean usesTransport,
        String pickupPoint,
        String routeName,
        String driverAssignment,
        String religion,
        String homeLanguage,
        String residencyType,
        String sponsorshipStatus,
        String feeCategory,
        String notes,
        @NotNull(message = "Required field missing: classId") @JsonAlias("classId") Long schoolClassId
) {
}
